### PR TITLE
LPS-55786 Check permission before updating portlet mode

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Laci,

The portal updated the portlet mode without checking permission, so users could access portlet modes they don't have permission to. (For more details see LPS-55786.)

I added permission check to prevent the erroneous behaviour.

Thanks for reviewing!

Pisti

### CODE REVIEW

**Comment by laszlocsontos** [comment]
Hi Pisti,

Some tests are failing, could you please check them. If failures are unrelated to your changes, let me know.

Thanks,
Laci

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Hi Laci,

All tests passed in 2nd round. :)

Thanks,
Pisti

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/149. [See changes here.](https://github.com/laszlocsontos/liferay-portal/compare/04e6288~1...04e6288) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
