### PR TITLE
LPS-56032 HttpUtil.normalizePath(uri) returns empty string for path /

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Laci,

Thanks for checking this!

Regards,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/881. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
