### PR TITLE
LPS-55706 Fix performance issue on Log in

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Laci,

I send this one for you, as @lipusz is on sick leave and he asked me to forward it to you: https://github.com/lipusz/liferay-portal/pull/75

It fixes a performance issue, as we updated the User_ table even there shouldn't be an update.

Regards,
Vilmos

### CODE REVIEW

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vilmospapp** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/159. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
