### PR TITLE
[TECHNICAL SUPPORT] LPS-55706 Reset failed login counter on succesful login

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @laszlocsontos,

I send this PR to you as you reviewed LPS-55258 as well and this issue came in sight when we were testing that fix.

This issue could affect the normal login as well, just the following default setting in portal.properties hides this problem and we haven't noticed it until LPS-55258 was commited.

```
users.update.last.login=true
```

I've also investigated the JAAS login and it seems that part also suffers from the same issue as LPS-55258 so I'll going to create a separate ticket for that and fix it with the pattern used in the aforementioned LPS with the same fix I applied in this PR for Basic and Digest authentication.

/cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Vili,

We have talked about it yesterday, and as I can see, you did what we agreed
in. Though, I didn't check it gracefully. If you want me to review
something next time, please, send me directly as I don't "cross-review"
pulls submitted to other engineers.

Thx,
Tibi

On Thu, May 21, 2015 at 1:11 AM, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 38 minutes 34 seconds
> See the following links for more information.
>
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/938/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/938/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-start(master)/938/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-start(master)/938/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/936/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/936/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-plugins(master)/803/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-plugins(master)/803/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend(master)/803/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend(master)/803/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-stop(master)/936/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-stop(master)/936/
>
> 7 Failures.
>
>    -
>    com.liferay.portlet.documentlibrary.store.AdvancedFileSystemStoreTest.testLogFailedDeletionWithVersionLabel
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/group=29,label_exp=!test-1-2/803/testReport/junit/com.liferay.portlet.documentlibrary.store/AdvancedFileSystemStoreTest/testLogFailedDeletionWithVersionLabel>
>
>    Unable to delete file {companyId=39939, repositoryId=39940, fileName=gik4oUnz, versionLabel=1.0} because it does not exist
>
>    junit.framework.AssertionFailedError: Unable to delete file {companyId=39939, repositoryId=39940, fileName=gik4oUnz, versionLabel=1.0} because it does not exist
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:103)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterClass(LogAssertionTestCallback.java:66)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCal
>     lback.java:74)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:40)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:69)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>
>     -
>    com.liferay.portlet.documentlibrary.store.AdvancedFileSystemStoreTest.testLogFailedDeletion
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/group=29,label_exp=!test-1-2/803/testReport/junit/com.liferay.portlet.documentlibrary.store/AdvancedFileSystemStoreTest/testLogFailedDeletion>
>
>    Unable to delete file {companyId=39985, repositoryId=39986, fileName=uHx2pTez} because it does not exist
>
>    junit.framework.AssertionFailedError: Unable to delete file {companyId=39985, repositoryId=39986, fileName=uHx2pTez} because it does not exist
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:103)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterClass(LogAssertionTestCallback.java:66)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:74)
>    	at com.liferay.portal.test.rule.callback.LogAsser
>     tionTestCallback.doAfterMethod(LogAssertionTestCallback.java:40)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:69)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>
>     -
>    com.liferay.portlet.documentlibrary.store.DBStoreTest.testLogFailedDeletionWithVersionLabel
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/group=31,label_exp=!test-1-2/803/testReport/junit/com.liferay.portlet.documentlibrary.store/DBStoreTest/testLogFailedDeletionWithVersionLabel>
>
>    Unable to delete file {companyId=30161, repositoryId=30162, fileName=KbS4wNPK, versionLabel=1.0} because it does not exist
>
>    junit.framework.AssertionFailedError: Unable to delete file {companyId=30161, repositoryId=30162, fileName=KbS4wNPK, versionLabel=1.0} because it does not exist
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:103)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterClass(LogAssertionTestCallback.java:66)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:74)
>    	at com.lifera
>     y.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:40)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:69)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>
>     -
>    com.liferay.portlet.documentlibrary.store.FileSystemStoreTest.testLogFailedDeletionWithVersionLabel
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/group=32,label_exp=!test-1-2/803/testReport/junit/com.liferay.portlet.documentlibrary.store/FileSystemStoreTest/testLogFailedDeletionWithVersionLabel>
>
>    Unable to delete file {companyId=27745, repositoryId=27746, fileName=bvXZB1LM, versionLabel=1.0} because it does not exist
>
>    junit.framework.AssertionFailedError: Unable to delete file {companyId=27745, repositoryId=27746, fileName=bvXZB1LM, versionLabel=1.0} because it does not exist
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:103)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterClass(LogAssertionTestCallback.java:66)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:74)
>
>
>
>
>
>
> *	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:40)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:69)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)   	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)   *
>
>     -
>    com.liferay.portlet.documentlibrary.store.FileSystemStoreTest.testLogFailedDeletion
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/group=32,label_exp=!test-1-2/803/testReport/junit/com.liferay.portlet.documentlibrary.store/FileSystemStoreTest/testLogFailedDeletion>
>
>    Unable to delete file {companyId=27791, repositoryId=27792, fileName=HKv5Oeg6} because it does not exist
>
>    junit.framework.AssertionFailedError: Unable to delete file {companyId=27791, repositoryId=27792, fileName=HKv5Oeg6} because it does not exist
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:103)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterClass(LogAssertionTestCallback.java:66)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.doAfterMethod(LogAssertionTestCallback.java:74)
>    	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback
>     .doAfterMethod(LogAssertionTestCallback.java:40)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:69)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>    	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:62)
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laszlocsontos/liferay-portal/pull/69#issuecomment-104068385>
> .
>



-- 

*Tibor LIPUSZ*

Senior Engineer, TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by vilmospapp** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/150. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
