### PR TITLE
[TECHNICAL SUPPORT] LPS-43440 Remove previews and thumbnails if folder is deleted in DBStore

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Laci,

I think this issue probable reproducible as well with FileSystemStore, but it's easier to observe with DBStore as it occurred there first.

I've tested it with different deep level structure like this:

```
FolderA
     |
     |-------FolderAB
     |               |
     |               |-------FolderAB1
     |               |
     |               |-------FolderAB2
     |                               |
     |                               |--------FolderAB21
     |
     |
     |-------FolderAC
                    |
                    |-------FolderAC1
                    |
                    |-------FolderAC2
                                    |
                                    |--------FolderAC21
```

Each folder had several multipage PDFs uploaded. I've waited until each thumbnail and preview is generated, then deleted the main folder and confirmed that each previews and thumbnails are removed. Also checked that other folders are not affected.

Please review my changes and if you find it correct please send it to Sergio.

Regards,
Vilmos

### CODE REVIEW

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
Hi Laci,

I try to retest it, but in local it compiles without any problem. So I'm confused a bit.

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/arboliveira/liferay-portal/pull/50. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/86. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
