### PR TITLE
LPS-57702 Remove unnecessary cache clearing

### PR DESCRIPTION
**Pull request by istvansajtos**
As per the [discussion on the engineering forum thread](https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/16025512) clearing the cache in JournalArticleLocalServiceImpl is unnecessary, because cache clearing is handled in JournalArticleModelListener.

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Cluster*Test classes fail without my commit as well.

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3563. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
