### PR TITLE
[TECHNICAL SUPPORT] LPS-57331Hibernate fix HHH-5927 Source Format Fix

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Laci,

This commit adds **source_formatter.ignore** files to the Hibernate source to avoid formatting on 3rd party files.

Regards,
Vilmos

### CODE REVIEW

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vilmospapp** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/1589. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
